python run_pretraining.py \
	--input_file=./pre_train_data/uniprot_data.tfrecord \
	--output_dir=./model/1kmer_model/ \
	--do_train=True \
	--do_eval=True \
	--bert_config_file=./bert_config_1.json \
	--train_batch_size=64 \
	--max_seq_length=128 \
	--max_predictions_per_seq=20 \
	--num_train_steps=12000000 \
	--num_warmup_steps=10 \
	--learning_rate=2e-5
