python run_classifier.py \
	  --task_name=COLA \
	    --do_train=true \
	      --do_eval=true \
	        --data_dir=./bert_classifier/tsv_data/ \
		  --vocab_file=./vocab/vocab.txt \
		    --bert_config_file=./bert_config.json \
		      --init_checkpoint=./bert_classifier/model.ckpt-10000000 \
		        --max_seq_length=128 \
			  --train_batch_size=32 \
			    --learning_rate=2e-5 \
			      --num_train_epochs=100.0 \
			        --output_dir=./bert_classifier/output/
